services:
  - type: web
    name: mpmc-datasheets
    env: node
    plan: free
    buildCommand: cd server && npm install --build-from-source sqlite3
    startCommand: cd server && node index.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
